name = "ConstraintLearning"
uuid = "4bd09668-9077-4be7-adc9-6307a490e6df"
authors = ["azzaare <jf@baffier.fr> and contributors"]
version = "0.1.2"

[deps]
CompositionalNetworks = "4b67e4b5-442d-4ef5-b760-3f5df3a57537"
ConstraintDomains = "5800fd60-8556-4464-8d61-84ebf7a0bedb"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
Evolutionary = "86b6b26d-c046-49b6-aa0b-5f0f74682bd6"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
QUBOConstraints = "110b7fcc-6942-4061-a625-86e03d1de7cf"
ThreadPools = "b189fb0b-2eb5-4ed4-bc0c-d34c51242431"

[compat]
CompositionalNetworks = "0.5"
ConstraintDomains = "0.3"
Dictionaries = "0.3"
Evolutionary = "0.11"
Memoization = "0.1"
QUBOConstraints = "0.1"
ThreadPools = "2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
