name = "ConstraintLearning"
uuid = "4bd09668-9077-4be7-adc9-6307a490e6df"
authors = ["azzaare <jf@baffier.fr> and contributors"]
version = "0.1.0"

[deps]
CompositionalNetworks = "4b67e4b5-442d-4ef5-b760-3f5df3a57537"
ConstraintDomains = "5800fd60-8556-4464-8d61-84ebf7a0bedb"
QUBOConstraints = "110b7fcc-6942-4061-a625-86e03d1de7cf"

[compat]
CompositionalNetworks = "0.4"
ConstraintDomains = "0.3"
QUBOConstraints = "0.1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
